### ISSUE TITLE
Simple documentation fix: CoffeeMachine example misses link to the example code

### ISSUE THREAD

**Issue by HansvdLaan** [LearnLib/learnlib#43]
I am currently learning LearnLib to use it for my bachelor thesis. When reading the documentation I found a small piece of information missing:

The example in https://github.com/LearnLib/learnlib/wiki/Instantiating-a-simple-learning-setup doesn't have a link to https://github.com/LearnLib/cav2015-example/blob/master/src/main/java/de/learnlib/example/cav2015/coffee/Example1.java. 

A direct link would be useful and would remove the need for additional searching to find the example.

**Comment by mtf90** [comment]
I am kind of hesitant to directly link to files of other projects, because things tend to go out-of-sync in the long run.

However, I see the point, that links to full-code examples are helpful. Thus I added one to the internal examples learnlib ships itself as well as a link to the (top-level) CAV'15 project.

Thanks for the feedback!
