### ISSUE TITLE
AbstractLStar may have nullpointer error

### ISSUE THREAD

**Issue by JohnYe** [LearnLib/learnlib#67]
The null pointer problem may occur when added symbols do not result in  state number increased when increasing study. It should change the new suffix verify. Since I have no rights for pushing code, I write the code should changed here.
In AbstractLStar.java file, the changes as follow:
```java
    protected boolean completeConsistentTable(List<List<Row<I>>> unclosed, boolean checkConsistency) {
        boolean refined = false;
        List<List<Row<I>>> unclosedIter = unclosed;
        do {
            while (!unclosedIter.isEmpty()) {
                List<Row<I>> closingRows = selectClosingRows(unclosedIter);
                unclosedIter = table.toShortPrefixes(closingRows, oracle);
                refined = true;
            }

            if (checkConsistency) {
                Inconsistency<I> incons;
                Word<I> lastNewSuffix = null;
                do {
                    incons = table.findInconsistency();
                    if (incons != null) {
                        Word<I> newSuffix = analyzeInconsistency(incons);
                        unclosedIter = table.addSuffix(newSuffix, oracle);
                        if (lastNewSuffix == null)
                        {
                        	lastNewSuffix = newSuffix;
                        }
                        else if (lastNewSuffix.equals(newSuffix))
                        {// new suffix consistent.
                        	break;
                        }
                    }
                } while (unclosedIter.isEmpty() && (incons != null));
            }
        } while (!unclosedIter.isEmpty());

        return refined;
    }
```

**Comment by mtf90** [comment]
Which version of LearnLib are you using? Could you maybe provide a small testcase that reproduces this error?

I tried to update one of our existing testcases based on your description: A new input symbol that behaves identically to an already existing one, so that the new symbol only causes new long-prefix rows in the observation table (no new states). However, I was not able to reproduce this error either on the latest `0.14.0` release or the current `develop` version.

**Comment by mtf90** [comment]
Any updates on this?

**Comment by mtf90** [comment]
Closing due to lack of feedback and non-reproducibility. 

If you think this issue still exists in the latest release / development version and (in the best case) can provide an example to reproduce this issue, feel free to re-open this ticket.

Also, consider our [Q&A mailing list](https://groups.google.com/forum/#!forum/learnlib-qa) if you have questions regarding the usage of LearnLib (or [AutomataLib](https://groups.google.com/d/forum/automatalib-qa)).
