### ISSUE TITLE
Moore machines

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/learnlib#72]
Hi,

I am trying to generalise some code to Moore machines. But I'm stuck at an quite early stage. Here is some code which works for DFAs. (Similar code works for Mealy.)
```
        CompactDFA<String> target = ...;
        MembershipOracle<String, Boolean> mqOracle = new DFASimulatorOracle<String>(target);
```

Trying to generalise to *Moore* machines gives:
```
        CompactMoore<String, String> target = ...;
        MembershipOracle<String, String> mqOracle = new SimulatorOracle<String, String>(target);
```

But this results in a compiler error:
```
Error:(40, 89) java: incompatible types: net.automatalib.automata.transducers.impl.compact.CompactMoore<java.lang.String,java.lang.String> cannot be converted to net.automatalib.automata.concepts.SuffixOutput<java.lang.String,java.lang.String>
```

Is there an easy way to work around this? Or should I redo a lot of work specifically for Moore machines?

**Comment by mtf90** [comment]
Hi Joshua,


the `SimulatorOracle` requires a delegate `SuffixOutput` automaton to answer the queries. When you look at the type hierarchy, `CompactMoore` (or `MooreMachine`s in general) implement/extend the `SuffixOutput<I, Word<O>>` interface, because they "answer" the input word with the complete output trace. So the correct type would be

```java
CompactMoore<String, String> target = null;
MembershipOracle<String, Word<String>> mqOracle = new SimulatorOracle<>(target);
```

If you want a DFA-style membership oracle which answers queries with the last, n-dimensional output symbol, you can wrap your oracle in a `SymbolOracleWrapper`. This wrapper is currently hidden behind the `MealyUtil#wrapWordOracle` method. To be fair, the naming is a little bit misleading (because `MooreMachine`s and -oracles aren't yet first-level citizens in LearnLib), but the implementation also works for Moore semantics.


Kind regards,
Markus

**Comment by Jaxan** [comment]
Hi Markus,

Thanks for the clarification! I have always considered DFA and Moore to be similar, so I didn't occur to me that the output for CompactMoore would be a word. I guess using words instead will also work fine in my case. (If not, I will try the `SymbolOracleWrapper`.)

Is there an overview of all the (basic) classes somewhere? I know that my java IDE will probably be able to do that, but I am not too familiar with java tooling. When looking at the superclasses / interfaces for `CompactMoore`, it is actually really hard to find `SuffixOutput`, it takes 4 steps to come to that conclusion...

Thanks again!
Joshua

**Comment by mtf90** [comment]
Hi Joshua,

usually the trace-semantics of Moore (and Mealy) machines prove beneficial in learning because they contain more information. Take for example the following observation table:

|   | ab |
| - | -- |
| u | xz |
| v | yz |

By using the complete suffix output, you can already differentiate between the two states. If you only use the last (state) output, you would need a second discriminator.


Regarding the type hierarchy, I agree that it may be overwhelming at first because it is quite complex. But once you get used to it, it actually feels nice because it allows you to pick only the concepts you need, which is especially useful when designing own automaton types.

Due to this complexity, we don't have a manually maintained overview of the types. My best bet would be to use one of your IDE's *type hierarchy* features. For example, in IntelliJ you can explore the supertype hierarchy of a base class (e.g. CompactMoore) or the subtype hierarchy of a general interface (e.g. UniversalDeterministicAutomaton). If you select a class you can find it under `Navigate > Type Hierarchy`.

![hierarchy](https://user-images.githubusercontent.com/7063944/89031989-ec54e180-d333-11ea-8a38-83ac19cb8b9d.png)

**Comment by Jaxan** [comment]
Hi Markus,

I got it working, finally. I have specialised the `AbstractExtensibleAutomatonLStar<A, I, D, S, T, SP, TP, AI>` type for Moore machines. I had to take `D = Word<O>` and `SP = O`, which was slightly confusing me at first. Thanks for the help!

About the suffix words: That is indeed a good point. But you can just as well take the set of columns to be suffix-closed (which was the case for the original L* algorithm). That will have the same effect. I believe one optimisation (by Rivest and Schapire?) was to actually not take a suffix closed set. Will this optimisation have no effect in the Mealy case?

Do I understand correctly that the learning algorithms for DFA and Moore machines with Boolean output will work differently because of this?


About the type hierarchy: Yes that helps a little. But unfortunately the information on generics is then missing. I guess there is currently no good way to represent all that information, given the size of the project.

**Comment by mtf90** [comment]
The (internal) learner classes are indeed on another level, because they need to marry the automaton types with the oracle types, etc. But glad to hear that you managed to figure it out.


For this particular case the suffix-closedness wouldn't help you, because it is the response to `a` that distinguishes the two states. So here, a prefix-closed set of discriminators would help (I believe Kearns & Vazirani investigated this approach).

In the end, I don't think it makes that much of a difference for the learning result itself, because the baseline for all (or most) AAL algorithms is to infer a complete and correct hypothesis anyway (given complete counterexamples).

What adds the spice to AAL in my opinion are the different kind of models that can be inferred and the performance of different learners (e.g. why use all suffixes if also a few discriminators do the job?). Here, I think, the more information you can extract from your systems, the more performance you can gain. I would argue that a DFA-style Moore machine (i.e. with boolean output) would on average require fewer membership queries than its DFA equivalent, because you can store more information (output words) in e.g. the observation table. Of course you pay for this with higher requirements to your SUL interface because you actually need a trace-like querying mechanism. But especially for reactive systems, one usually has these mechanisms available.

**Comment by Jaxan** [comment]
You are absolutely right, my mistake. Thanks again for clarifying!

**Comment by mtf90** [comment]
Is this issue resolved for you then?

**Comment by Jaxan** [comment]
Yes, thanks!

I also got a version working with only the last symbol (not the suffix). But that was way more involved.

**Comment by mtf90** [comment]
Great to hear. Just for future reference: If you have any questions regarding the usage of LearnLib (or AAL in general) feel free to use our [Q&A mailing list](https://github.com/LearnLib/learnlib#mailing-lists) so that we can keep the issue tracker on GitHub for code-related issues.

Cheers
