### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by VishalPatel43** [LearnLib/learnlib#94]
I did both IntelliJ IDEA and VS Code get the error while build the project.
System: Macbook Air M1
Use Java 17 and Maven 3.9.5

System: Ubuntu 22.04
Use Java 17 and Maven 3.6.3

**IntelliJ IDEA**
<img width="1440" alt="Screenshot 2023-10-10 at 17 26 19" src="https://github.com/LearnLib/learnlib/assets/123478469/74fad7ed-908b-440a-9d60-46c1a6f46f79">

**VS CODE**
<img width="1440" alt="Screenshot 2023-10-10 at 17 30 09" src="https://github.com/LearnLib/learnlib/assets/123478469/cdcd105f-21d3-4e43-9cd8-7c82e238a54c">

**Comment by mtf90** [comment]
The problem is that you are trying to build the development version of LearnLib which also requires the development version of AutomataLib. You can either clone and import (the development version of) [AutomataLib](https://github.com/LearnLib/automatalib) as well (which makes sense if you want to work on a feature spanning both libraries -- we usually keep them in sync with each other) or include the [snapshot repo](https://github.com/LearnLib/automatalib/wiki/Using-Development-Versions) which contains the development artifacts of AutomataLib via CI/CD.

**Comment by VishalPatel43** [comment]
<img width="1440" alt="Screenshot 2023-10-11 at 13 31 54" src="https://github.com/LearnLib/learnlib/assets/123478469/b1399d81-d10c-40b3-8e63-e938fb9c8248">
<img width="1440" alt="Screenshot 2023-10-11 at 13 32 02" src="https://github.com/LearnLib/learnlib/assets/123478469/32b51b72-ce88-4529-b2e7-db42e3a40ac4">

**Comment by mtf90** [comment]
This appears to be a problem with [ADDLib](https://gitlab.com/scce/add-lib) which is used internally by the M3C model checker and currently does not support the M1 architecture. I'll relay the information to the developers and see what they have to say.

For now, you could either compile the AutomataLib without tests (e.g., `mvn clean install -DskipTests`), use the pre-compiled artifacts from the SNAPSHOT repo (if you don't need changes in AutomataLib), or use your Ubuntu Linux setup.
